wip use serviceloader to find result providers
ingef/conquery pull request #2862
Opened 2022-12-16 15:33 UTC by thoniTUB

2022-12-19 14:35 UTC, awildturtok requested changes
Sieht gut aus

2022-12-19 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/ArrowServiceConfig.java
> +@CPSType(base = PluginConfig.class, id = "ARROW")
Wird noch verwendet?

2022-12-19 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/CsvServiceConfig.java
> +		super(false, -1);
Wofür ist der ungültige CTor da?

2022-12-19 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/config/PluginConfig.java
> + * TODO Doku
🥇

2022-12-19 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/service/AbstractResultProviderConfig.java
> +	private int priority = 0;
Was ist min?

2022-12-19 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/service/ArrowResultService.java
> +	public void setConfig(PluginConfig config) {
Du kannst Config theoretisch als Generic machen, das ist dann etwas sauberer hier. Hat aber vmtl null echten Effekt

2024-08-01 08:20 UTC, thoniTUB commented
Serviceloader sind hier kein praktischer Ansatz, da man jars zur Runtime nicht so einfach zusammen stöpseln kann

2024-08-01 08:20 UTC, closed without merging