map keycloak groups to conquery groups
ingef/conquery pull request #2928
Opened 2023-02-10 07:43 UTC by thoniTUB

2023-02-14 10:10 UTC, awildturtok requested changes

2023-02-14 14:43 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/keycloak/GroupUtil.java
> +			if (group.path().startsWith(groupParent.path())) {
Wie meinst du das, wie sollte ich hier einen Separator nutzen?

2023-02-14 14:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/keycloak/GroupUtil.java
> +				if (foundMatchingPath) {
genau, das mit den mehrer Groupen handle ich gerade an anderer stelle, aber ich kann es hiereinziehen

2023-02-14 14:49 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/keycloak/GroupUtil.java
> +			if (group.path().startsWith(groupParent.path())) {
hätte gedachtt, dass es `.startsWith(groupParent.path() + "/")` sein müsste

2023-02-14 15:05 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/IntrospectionDelegatingRealm.java
> +		if (providedAudiences.contains(expectedAudience)) {
Danke!, da war im test auch noch die falsche audience gesetzt weshalb das durchgegangen ist

2023-02-14 15:38 UTC, awildturtok approved these changes

2023-02-14 15:38 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/IntrospectionDelegatingRealm.java
> +		catch (java.text.ParseException e) {
FQN?

2023-02-14 15:38 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/keycloak/GroupUtil.java
> +	 * <pre>[bb, b]</pre>
Ok, danke jetzt verstehe ich es

2023-02-16 13:01 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/keycloak/GroupUtil.java
> +			if (group.path().startsWith(groupParent.path())) {
Guter Punkt, das ergänze ich noch

2023-02-16 15:01 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/auth/oidc/IntrospectionDelegatingRealm.java
> +		catch (java.text.ParseException e) {
Das ist vmtl. ein fehler vom Nimbus SDK. Die haben ihre eigene ParseException, die auch von einer Funktion hier geworfen wird, aber anscheinend werfen sie auch die java.text.ParseException an dieser Stelle. Ich kann da mal nachfragen

2023-02-17 08:50 UTC, merged