inject storage into managed execution, separate internal executions
ingef/conquery pull request #2941
Opened 2023-02-15 14:21 UTC by thoniTUB

2023-02-16 10:15 UTC, awildturtok requested changes

2023-02-16 10:15 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/query/QueryResolveContext.java
>  	}
hast du doch schon als getter?

2023-02-16 10:15 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/ResultExcelResource.java
> +			@QueryParam("pretty") @DefaultValue("true") boolean pretty) {
Bitte defaultValue auch beim rest definieren, auch wenn sie ggf false sind

2023-02-16 10:18 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/forms/Form.java
> -	public abstract Map<String, List<ManagedQuery>> createSubQueries(DatasetRegistry datasets, User user, Dataset submittedDataset);
Die ist jetzt in ein Interface gewandert das von internen Formularen genutzt wird

2023-02-16 10:19 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/TableExportQuery.java
> -@RequiredArgsConstructor(onConstructor = @__({@JsonCreator}))
Das war das alte Konstrukt soweit ich weiß

2023-02-16 10:19 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/commands/ManagerNode.java
> +				);
Ich packs in die DatasetRegistry

2023-02-16 10:20 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/ExternalFormBackend.java
> + * Configuration for a generic form backend server.
Das ist erstmal rausgeflogen und kommt dann im nachfolge PR

2023-02-16 10:22 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/query/QueryResolveContext.java
>  	}
Dataset wollte ich noch rauslöschen, weil es sich aus Namespace ableitet

2023-02-21 10:12 UTC, awildturtok approved these changes

2023-02-24 12:26 UTC, merged