Currency Input update
ingef/conquery pull request #3021
Opened 2023-04-04 14:07 UTC by fabian-bizfactory

Draft, needs to be discussed internally

2023-04-17 09:45 UTC, Kadrian requested changes
I think the right way to do this would be
1) let's call the currency config field `unit` (instead of `suffix` or `prefix` and let's not use spaces within the string (the backend shouldn't be involved in the details on how or where the unit gets displayed in the frontend, so already calling it `prefix` wasn't very well done from our side)
2) in the frontend, where we render `NumericFormat`, let's pass 
```
suffix={" " + currencyConfig.suffix}
```
because the fact that we're using a **space** for separating the value form the unit is an implementation detail

2023-04-17 10:28 UTC, Kadrian commented on frontend/src/js/ui-components/CurrencyInput.tsx
> +      suffix={" " + currencyConfig?.unit}
Easier like this:
```suggestion
     {...currencyConfig}
      suffix={" " + currencyConfig.unit}
```

( I think we can safely make `currencyConfig` **non-optional** in `CurrencyInput` )

2023-04-17 10:29 UTC, Kadrian commented on frontend/src/js/entity-history/timeline/EventCard.tsx
> +                      suffix={" " + currencyConfig.unit}
Same here, we should be able to **spread** currencyConfig and override `suffix`

2023-04-17 10:29 UTC, Kadrian approved these changes
👍

2023-04-18 08:24 UTC, merged

2023-04-19 07:22 UTC, awildturtok commented
This PR broke things internally, please notify me if you change something in the backend's source code. The config is not just a static file, but can be provided and overriden at start time. Changing the name caused requires us to change it in our config as well.

2023-04-19 07:53 UTC, fabian-bizfactory commented
> This PR broke things internally, please notify me if you change something in the backend's source code. The config is not just a static file, but can be provided and overriden at start time. Changing the name caused requires us to change it in our config as well.

Hey, I am so sorry about that! I will double check all the PRs in the future, so that won't happen again. If there is anything needed, please let me know.