added year and month selection to Datepicker
ingef/conquery pull request #3070
Opened 2023-05-11 08:17 UTC by MarcoKorinth

2023-05-15 13:39 UTC, Kadrian requested changes
Really good work here, nice and simple! I've added some rather organizational comments, would be happy if you could address them. 

Side note / unrelated to this PR: while testing I've wondered why the date picker sometimes highlights certain dates that are **neither** today **nor** related to the app somehow? Have you seen this too?

2023-05-16 14:52 UTC, awildturtok commented on frontend/src/js/ui-components/InputDate/CustomHeader.tsx
> +const yearOptions: SelectOptionT[] = [...Array(10).keys()]
We're sending the frontend a variable called `observationPeriodMin` - just for the preview - that demarcates a realistic first day. Maybe we move it up into the previewconfig so you both can use it?

2023-05-16 16:02 UTC, Kadrian requested changes

2023-05-16 16:02 UTC, Kadrian commented on frontend/src/js/common/helpers/dateHelper.ts
> +  const locale = i18next.language === "de" ? de : enGB;
Could you reuse `useDateLocale` from some lines above (+ make these functions hooks)? That way, once we allow switching language, it will still work.

2023-05-17 19:29 UTC, Kadrian approved these changes
Nice, looks good to me!

2023-05-23 12:12 UTC, merged