fix: datepicker blocks input field
ingef/conquery pull request #3164
Opened 2023-08-31 12:56 UTC by MarcoKorinth

# Changes
- fixed bug: datepicker opens over input field
- datepicker only opens after clicking the new calendar icon inside the input field
- datepicker starts in year selection mode by default

2023-09-04 10:54 UTC, Kadrian requested changes
I'd be happy if you tried reusing `IconButton`, otherwise looks pretty good!

2023-09-04 10:54 UTC, Kadrian commented on frontend/src/js/common/helpers/mergeRefs.ts
> +};
Hmmm in other implementations I can see them using a `MutableRefObject` type from React. You probably copied the code below from somewhere, right? I guess I wonder whether we shouldn't just use some external implementation like https://github.com/gregberge/react-merge-refs but up to you

2023-09-05 08:22 UTC, Kadrian approved these changes
Nice!
Slightly funny that the year picker half way overlays the day picker if there aren't that many years. But I hope that will just be fixed in the backend with more available years, cc @awildturtok 

Here's a small suggestion https://github.com/ingef/conquery/pull/3166

2023-09-06 09:24 UTC, merged

2023-09-06 10:03 UTC, awildturtok commented
@MarcoKorinth kannst du bitte die dependencies auf eva seite gleichstellen?