Keep row prefix constant when reordering
ingef/conquery pull request #3176
Opened 2023-09-19 15:43 UTC by fabian-bizfactory

2023-09-25 10:03 UTC, Kadrian requested changes
Hmm, what you'd be doing here is "hard-coding" the name `row_prefix`. So `rowPrefixField` is an optional select field with a dynamic name, and in this case it might be `row_prefix`, but in other fields in might be another name, so we'll have to rely on `field.rowPrefixField.name` for the prefix field name.

Guess what I'd try instead would be to
- pass down a `rowPrefixFieldname` and maybe the `row` itself from the FormConceptGroup to the FormConceptNode
- add both to the dragContext
- get them both from the dragContext in dropBetween
- if defined, get the prefix field value from the row + rowPrefixFieldname and pass a modified `newValue` to `insertValue()`

Does that make sense?

2023-09-26 12:04 UTC, fabian-bizfactory commented
> Hmm, what you'd be doing here is "hard-coding" the name `row_prefix`. So `rowPrefixField` is an optional select field with a dynamic name, and in this case it might be `row_prefix`, but in other fields in might be another name, so we'll have to rely on `field.rowPrefixField.name` for the prefix field name.
> 
> Guess what I'd try instead would be to
> 
>     * pass down a `rowPrefixFieldname` and maybe the `row` itself from the FormConceptGroup to the FormConceptNode
> 
>     * add both to the dragContext
> 
>     * get them both from the dragContext in dropBetween
> 
>     * if defined, get the prefix field value from the row + rowPrefixFieldname and pass a modified `newValue` to `insertValue()`
> 
> 
> Does that make sense?

I just implemented some changes to this PR. `rowPrefixFieldname` is only passed. I don't think the `row` needs to be passed `props.value[movedFromAndIdx]` returns the `row` as well. 

Please let me know what you think

2023-09-26 12:52 UTC, Kadrian commented
Would that work with concepts dragged in from other fields as well?

2023-09-26 12:56 UTC, fabian-bizfactory commented
No, but that wasn't possible in the previous version either. If we would allow that we would need to take in the possible values for the prefix into account, wouldn't we? To catch the case of the prefixes having different possible values.

2023-10-02 08:38 UTC, awildturtok commented on frontend/src/js/external-forms/form-concept-group/FormConceptGroup.tsx
> +                // Having a row prefix is a special property that is only used in an edge case form. We only need to pass it
```suggestion
                // Having a row prefix is a special property that is only used in an edge case form, used for tagging concepts. We only need to pass it
```

2023-10-02 08:40 UTC, awildturtok commented on frontend/src/js/external-forms/form-concept-group/FormConceptGroup.tsx
> +                if (
puuh, das sieht gut so aus, aber kP ob das bei dir Nebeneffekte hat, die nicht offensichtlich sind.

zB darf newValue mutable behandelt werden?

2023-10-02 09:33 UTC, fabian-bizfactory commented on frontend/src/js/external-forms/form-concept-group/FormConceptGroup.tsx
> +                if (
Danke, da hast du Recht, dass prop sollte so eigentlich nicht geändert werden. Ich habe gerade eine Version gepusht die ein deep copy umsetzt (mit json)

2023-10-16 11:03 UTC, Kadrian approved these changes
@fabian-bizfactory I've cleaned up some of the logic, check my last commit. Was a bit easier than trying to explain. Looks good otherwise.

2023-10-17 06:28 UTC, merged