Implements endpoint to fetch query result statistics
ingef/conquery pull request #3220
Opened 2023-11-16 08:43 UTC by awildturtok

2023-11-16 08:45 UTC, awildturtok commented
Median fehlt noch

2023-11-16 10:34 UTC, thoniTUB requested changes

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Okay dieser SamplePicker hat mich sehr verwirrt. Ich dachte erst hier werden nur 80 Samples für die Statistik ausgewertet, aber er wird zum Sammeln der Beispielwerte genutzt.

Bitte doku.

Ich verstehe noch nicht warum du hier Random nimmst. Dadurch variiert die Menge an Samples doch von der Ergebnismenge:
- viele Ergebnisse -> wenig Samples
- wenig Ergebnisse -> viele Samples

Möchte man nicht lieber eine konstante/upper Bound an Samples haben, anstatt eines inversen Verhältnisses

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
> +		}
```suggestion
	public static ColumnStatsCollector getStatsCollector(ResultInfo info, final PrintSettings printSettings, BooleanSupplier samplePicker) {
		ResultType type = info.getType();
		if (type instanceof ResultType.IntegerT) {
			return new NumberColumnStatsCollector(info.defaultColumnName(printSettings), info.userColumnName(printSettings), info.getDescription(), type, samplePicker);
		}
```

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
> +	}
Als Record vllt?

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/ColumnConfig.java
> + * Describes how rows are mapped for {@link EntityIdMap}/{@link AdmDatasetProcessor#setIdMapping(java.io.InputStream, com.bakdata.conquery.models.worker.Namespace)}.
admin->adm 😢

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/types/ResultType.java
> +
unused

2023-11-16 10:34 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/QueryResource.java
> +		query.awaitDone(1, TimeUnit.SECONDS);
ReturnVal überprüfen

2023-11-16 10:37 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Es sollten immer ungefähr 80 random samples sein

2023-11-16 11:13 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Stimmt, du hast recht bei der Anzahl.

2023-11-16 11:17 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
ich kann das etwas ausführlicher schreiben als Kommentar, aber ich hab davor ungefähr 20min auf den Bildschirm gestarrt, irgendwie wahrscheinlichkeiten auszurechnen, bis ich gemerkt habe, dass ich das so ziemlich transparent hinkriege ohne viel hirnschmalz.

2023-11-16 11:23 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Kannst du nicht von vornherein bestimmen, welche Samples gewählt werde sollen, z.B:
```java
final int[] sampleIndexes = random.ints(0, managedQuery.getLastResultCount().intValue()).limit(requiredSamples).toArray();
```

2023-11-16 11:27 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
dann muss ich aber den Zustand im collector tracken, das ist unschön, dazu wären die samples dann nicht mehr unabhängig je collector.

2023-11-16 11:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +				out.addAll(extractValidityDate(listT.getElementType(), date));
ja war einfacher als das anders zu lösen und macht keine Nachteile

2023-11-16 11:29 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
> +		}
das ist nicht richtig, weil der type bei list geflattet wird

2023-11-16 11:37 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
`DateColumnStatsCollector` zählst du schon mit wieviele Werte schon gezählt wurden, das könntest du für den `NumberColumnStatsCollector` doch auch machen.

Was ist der Vorteil, wenn die Samples unabhängig sind? Dann würden, abgesehen von null Werten, überall gleich viele Werte existieren. Das ist doch praktisch wenn man so ein oberes Limit verbindlich festlegen kann.

2023-11-16 11:41 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Ich sehe immer noch nicht den Vorteil, ich würde es erstmal so lassen, das ist eine relativ überschaubare Implementierung.

2023-11-16 11:47 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
> +	}
Wir benutzen die nur zum sharen der Felder, das kann dann leider kein record sein.

2023-11-16 11:48 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
Ja lass es so ich sehe nur gerade diese Nachteile:
- Zufallsvariable beeinflusst gleichzeitig welche Zeilen gesampled werden und wieviele.
- Anzahl der Samples ist theoretisch nur an die Menge Zeilen gebunden
- Anzahl der Samples kann von Spalte zu Spalte variiren, was bei der Darstellung im Frontend vielleicht komisch aussieht

2023-11-16 11:51 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
> +		}
Stimmt, habe ich übersehen

2023-11-16 11:52 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final BooleanSupplier samplePicker = () -> random.nextInt(managedQuery.getLastResultCount().intValue()) < requiredSamples;
> Anzahl der Samples kann von Spalte zu Spalte variiren, was bei der Darstellung im Frontend vielleicht komisch aussieht

das ist kein problem, die samples werden nur zur visualisierung einr kurve verwendet. Die alternative wäre die kurve serverseitig zu rendern

2023-11-16 16:38 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/resources/api/QueryResource.java
> +		query.awaitDone(1, TimeUnit.SECONDS);
> ReturnVal überprüfen

![grafik](https://github.com/ingef/conquery/assets/1553491/02d21277-5d27-4892-b707-8447a2202113)

so?

2023-11-20 07:15 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/QueryResource.java
> +		query.awaitDone(1, TimeUnit.SECONDS);
👌

2023-11-23 08:08 UTC, thoniTUB approved these changes
Ein paar kleine Sachen

2023-11-23 08:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
Die vielen Collectors hier sind jetzt im API package, aber werden eigentlich nicht über die API exposed nur die `ColumnDescription`

2023-11-23 08:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/resources/api/QueryResource.java
> +			return Response.status(Response.Status.CONFLICT).build(); // Request was submitted too early.
Ich glaube, dass du deinen Kommentar in die Response reinschreiben kannst. Das erleichtert das debuggen

2023-11-23 08:08 UTC, thoniTUB commented on backend/src/test/resources/tests/endpoints/apiEndpointInfo.json
> +  },
Gerne zu den anderen `/query/...` Endpunkten einordnen

2023-11-23 08:49 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ListColumnStatsCollector.java
> +	private final ColumnStatsCollector<T> underlying;
> Sammelt der underlying nicht potentiell zu viele Samples?

argh, du hast recht, sogar ordentlich zu viele. Das dürfte kein riesen problem sein, muss ich mir aber anschauen. Danke!

2023-11-23 08:58 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final AtomicReference<CDateRange> span = new AtomicReference<>(null);
Ah ich hattes es eher auf die AtomicReference abgesehen, denn solange der Stream nicht parallel ist reicht es doch für die closure, dass das Object CDateSet/CDateRange final ist

2023-11-23 09:00 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/QueryProcessor.java
> +		final AtomicReference<CDateRange> span = new AtomicReference<>(null);
ja, das stimmt, aber CDateRange ist ja immutable, deswegen muss ich das tatsächlich in einer AtomicRef austauschen.

2023-11-23 14:35 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/statistics/ColumnStatsCollector.java
habs nach models.query verschoben, guter Hinweis, danke

2023-11-27 07:04 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/config/ColumnConfig.java
> + * Describes how rows are mapped for {@link EntityIdMap}/{@link AdmDatasetProcessor#setIdMapping(java.io.InputStream, com.bakdata.conquery.models.worker.Namespace)}.
Sollen wir hier nochmal reinschauen in das Problem?

2023-12-07 11:32 UTC, awildturtok commented
@thoniTUB ich werde die Openapi nachliefern. Damit die biz schonmal weiter testen kann merge ich den stand so.

2023-12-07 11:54 UTC, merged