Feature/resolve from storage
ingef/conquery pull request #3441
Opened 2024-05-15 06:39 UTC by thoniTUB

This pr makes the CentralRegistry obsolete, by resolving ids directly from the storage.

Before, the CentralResgistry held all objects in Memory so no memory optimized caching is possible.
Removing the registry removes one central point were hard references to all objects where held.

The CentralRegistry was used by deserializers (MetaIdReferenceDeserializer,  NsIdReferenceDeserializer) to resolve incomming Ids in JSONs to concrete objects.
The CentralRegistry was however not a singleton, as every Storage (MetaStorage, NamespaceStorage, WorkerStorage) had one.
It is replaced by the NsIdResolver interface, which is implemented by NamespaceStorage, WorkerStorage and DatasetRegistry.

The MetaIdReferenceDeserializer just uses the MetaStorage directly.

2024-05-16 07:31 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/filter/FilterValue.java
Hier habe ich den Deserializer angepasst, so dass nicht erst zum Zeitpunkt der Deserializierung der IdResolver aus den Injectables rausgesucht wird, sondern schon während der Instantiierung

2024-05-16 11:37 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/mina/BinaryJacksonCoder.java
> +	public BinaryJacksonCoder(NsIdResolver datasets, Validator validator, ObjectMapper objectMapper) {
IdResolveContext konnte MetaId und NamespacedIds resolven. MetaIds werden aber gar nicht gebraucht in der Kommunikation zwischen Manager und Shards, deshalb gibt es hier nur einen NsIdResolver

2024-05-23 06:32 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/storage/MetaStorage.java
> +	public <ID extends Id<VALUE>, VALUE extends Identifiable<?>> VALUE get(ID id) {
Diese get Methoden in den Storages imitieren einfach das ehemalöige getOptional der CentralRegistry.

2024-05-23 13:39 UTC, SebChmie approved these changes
Sieht gut aus 😃

2024-05-29 06:07 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/storage/NamespacedStorage.java
>  	private void decorateDatasetStore(SingletonStore<Dataset> store) {
Die Methoden wurden für eine etwaige Initialisierung eines Objektes angelegt. Viele Objekte müssen aber nicht initialisiert werden und für andere habe ich denke ich eine bessere Lösung gefunden. Also die Funktionen können potentiell weg

2024-05-29 06:08 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/datasets/PreviewConfig.java
>  	public boolean isSelectsUnique() {
oh das kann natürlich sein, mir wurde die Warnung nicht angezeigt.

2024-06-04 09:13 UTC, awildturtok requested changes
-300 Zeilen code und es ist jetzt direkter gekoppelt, nice!

2024-06-04 09:13 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/worker/DatasetRegistry.java
> +                .add(this.getClass(), this);
sind beide injections notwendig?

2024-06-04 09:13 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/api/form/config/FormConfigTest.java
> +		// TODO
noch offen?

2024-06-04 09:13 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/SerializationTests.java
> +		workerStorage.addBucket(bucket);
fett

2024-06-04 09:13 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/models/types/SerialisationObjectsUtil.java
> +	public static TreeConcept createConcept(Dataset dataset, NamespacedStorage ... storages) {
wieso können das mehrere Storages sein?

2025-01-08 10:32 UTC, thoniTUB commented
This was a draft which is implemented now

2025-01-08 10:32 UTC, closed without merging