Feature/rewrite caching
ingef/conquery pull request #3455
Opened 2024-05-29 13:29 UTC by thoniTUB

Instead of a wrapping CachedStore that will hold all objects in memory over time, this uses a configurable Cache, for resolved ids.

2024-06-04 12:28 UTC, awildturtok requested changes
Ich kann einen großen Teil wegen github limitierungen nicht reviewen. Die Änderungen sehen im großen OK aus. Was ich nicht ganz durchschaut habe ist, warum du immernoch NsIdRef deserializer hast

2024-06-04 12:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/SecondaryIdDescription.java
>  	@View.ApiManagerPersistence
die Anno kann dann weg

2024-06-04 12:28 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/datasets/concepts/select/concept/specific/ExistsSelect.java
>  	private Set<Table> collectRequiredTables() {
kannst hier vermutlich auch die Id rausgeben?

2024-06-04 12:30 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/View.java
> +	interface TestNoResolve extends View {
kommt weg, dafür hatte ich die Placeholder* Klassen eingeführt, aber auch diskutabel ob das der saubere weg ist

2024-06-04 12:31 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/mina/CQProtocolCodecFilter.java
> +				Thread.sleep(2000);
ups, das gehört gar nicht in den PR

2024-07-19 10:18 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/io/jackson/serializer/CBlockDeserializer.java
> +		// If we cache we don't need to optimize this
Weil der CBlock wieder aus dem Cache geschmissen werden kann. Dann können wir uns die Zeit hier sparen beim parsen

2025-01-08 10:34 UTC, closed without merging