Fix ConceptColumnSelect conversion if there is only 1 connector
ingef/conquery pull request #3495
Opened 2024-07-15 18:26 UTC by jnsrnhld

2024-07-24 12:30 UTC, awildturtok requested changes

2024-07-24 12:30 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/sql/conversion/model/select/ConceptColumnSelectConverter.java
> +	private static boolean only1ConnectorSelected(ConceptSqlTables tables) {
isSingleConnector?

2024-07-25 09:12 UTC, jnsrnhld commented on backend/src/test/resources/tests/sql/selects/distinct/expected.csv
> +5,{2012-01-01/2012-01-04},"{f,f ,m,m }"
Das ist aus dem [DistinctSelect PR](https://github.com/ingef/conquery/pull/3494) und war hier nur drin, weil noch nicht mit dem aktuellen Stand von `develop` gemerged. Das müsste doch aber passen weil das mit Whitespace distinct ist oder nicht?

2024-07-25 09:35 UTC, awildturtok commented on backend/src/test/resources/tests/sql/selects/distinct/expected.csv
> +5,{2012-01-01/2012-01-04},"{f,f ,m,m }"
wir trimmen whitespaces eigentlich, deswegen müssten die schon identisch sein

2024-07-25 09:38 UTC, jnsrnhld commented on backend/src/test/resources/tests/sql/selects/distinct/expected.csv
> +5,{2012-01-01/2012-01-04},"{f,f ,m,m }"
Ich hab das von diesem Aggregator-Test hier übernommen: https://github.com/ingef/conquery/blob/develop/backend/src/test/resources/tests/aggregator/VALUES_AGGREGATOR/expected.csv

2024-07-25 09:39 UTC, awildturtok commented on backend/src/test/resources/tests/sql/selects/distinct/expected.csv
> +5,{2012-01-01/2012-01-04},"{f,f ,m,m }"
uff. Ich schaus mir nochmal an, das dürfte eigentlich nicht passieren  :D

2024-07-29 12:44 UTC, awildturtok approved these changes

2024-07-29 14:04 UTC, merged