Implement external ID lookup for SQL mode
ingef/conquery pull request #3496
Opened 2024-07-16 09:57 UTC by jnsrnhld

2024-07-16 13:51 UTC, awildturtok reviewed
Ich schaue mir das morgen nochmal im Detail an.

2024-07-16 13:51 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/apiv1/query/concept/specific/external/EntityResolverUtil.java
> +		if (onlySingles) {
kannst du das bitte inverten

2024-07-16 13:51 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/integration/json/ConqueryTestSpec.java
> +								.label(Map.of(Locale.GERMANY, "result"))
```suggestion
								.label(Map.of(Locale.ROOT, "result"))
```

2024-07-16 13:51 UTC, awildturtok commented on backend/src/test/java/com/bakdata/conquery/integration/json/ConqueryTestSpec.java
> +								.primaryId(true)
bitte von entitity und nicht person sprechen.

2024-07-25 07:56 UTC, awildturtok requested changes
sieht sonst gut aus.

2024-07-25 07:56 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/mode/local/SqlEntityResolver.java
> +				final EntityIdMap.ExternalId externalId = reader.apply(row);
Glaube der Lesbarkeit halber solltest du die ExternalId von EntityIdMap entkoppeln oder zumindest die IdReader von der EntityIdMap. Ich lese den Code gerade und rätsele die ganze Zeit was du mit der EntityIdMap machst (die du ja nicht zur verfügung haben wirst).

2024-07-25 09:25 UTC, jnsrnhld commented on backend/src/main/java/com/bakdata/conquery/mode/local/SqlEntityResolver.java
> +				final EntityIdMap.ExternalId externalId = reader.apply(row);
Guter Punkt 👍

2024-07-25 09:41 UTC, awildturtok approved these changes

2024-07-25 09:48 UTC, merged