Adds timeout check to ClusterHealthCheck
ingef/conquery pull request #3532
Opened 2024-08-21 14:13 UTC by thoniTUB

2024-08-21 14:20 UTC, awildturtok requested changes

2024-08-21 14:20 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/worker/ClusterHealthCheck.java
> +															   .filter((status) -> heartbeatTimeout.minus(Duration.between(now, status.getLastStatusTime()))
warum benutzt du hier nicht age?

2024-08-21 14:20 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/models/worker/ClusterHealthCheck.java
> +															   .filter((status) -> heartbeatTimeout.minus(Duration.between(now, status.getLastStatusTime()))
dann könntest du hier comparison oä benutzen

2024-08-22 06:43 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/worker/ClusterHealthCheck.java
> +															   .filter((status) -> heartbeatTimeout.minus(Duration.between(now, status.getLastStatusTime()))
Das mit dem age war mein erster Ansatz, aber das war der JobmanagerStatus, nicht, wann die letzte Nachricht vom Shard kam. Im ShardNodeInformation gab es getLastStatusTime

2024-08-22 07:00 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/models/worker/ClusterHealthCheck.java
> +															   .filter((status) -> heartbeatTimeout.minus(Duration.between(now, status.getLastStatusTime()))
Und wir haben hier java Durations nicht die von Dropwizard

2024-08-22 07:40 UTC, awildturtok approved these changes

2024-08-22 08:35 UTC, merged