Use dw DataSize for validation
ingef/conquery pull request #3642
Opened 2024-12-17 11:31 UTC by thoniTUB

2024-12-17 11:34 UTC, awildturtok requested changes

2024-12-17 11:34 UTC, awildturtok commented on backend/src/main/java/com/bakdata/conquery/util/validation/DataSizeMaxValidator.java
> +public class DataSizeMaxValidator implements ConstraintValidator<Max, DataSize> {
io.dropwizard.validation.MaxDataSize

gibt es schon

2024-12-17 11:35 UTC, thoniTUB commented on backend/src/main/java/com/bakdata/conquery/util/validation/DataSizeMaxValidator.java
> +public class DataSizeMaxValidator implements ConstraintValidator<Max, DataSize> {
Ups, den habe ich übersehen. Danke!

2025-01-22 14:55 UTC, awildturtok commented
auch noch todo?

2025-01-27 14:42 UTC, awildturtok approved these changes

2025-02-03 10:13 UTC, merged